### ISSUE TITLE
is shapes/modifier incomplete? 

### ISSUE THREAD

**Issue by Aidosmf** [LottieFiles/lottie-docs#17]
Seems like https://github.com/LottieFiles/lottie-docs/blob/main/docs/schema/shapes/modifier.json is not necessary or incomplete?
1. Modifier's `ty` equals to `null` and it is not part of the ShapeType in https://github.com/LottieFiles/lottie-docs/blob/main/docs/schema/shapes/shape-element.json#L19? 
2. A shape that extends `shape/modifier` overwrites `ty` anyway, for example, in `shapes/repeater`: https://github.com/LottieFiles/lottie-docs/blob/main/docs/schema/shapes/repeater.json#L13 

Thus, should we delete `shapes/modifier` and extend `shapes/shape-element` instead of it?

**Comment by mbasaglia** [comment]
yea it's an artifact from when I generated the schema

**Comment by mbasaglia** [comment]
Fixed now
