### ISSUE TITLE
duplicate 'so' property name in bevel-emboss-style

### ISSUE THREAD

**Issue by Aidosmf** [LottieFiles/lottie-docs#24]
There is a duplicate property name in "Soften" and "Shadow Opacity".
File: https://github.com/LottieFiles/lottie-docs/blob/main/docs/schema/styles/bevel-emboss-style.json

**Comment by mbasaglia** [comment]
I made a pull request to rename one of them https://github.com/bodymovin/bodymovin-extension/pull/125

**Comment by mbasaglia** [comment]
All done
