### ISSUE TITLE
Please list sources 

### ISSUE THREAD

**Issue by Loque-** [LottieFiles/lottie-docs#28]
> This is because there's already a lot of documentation for creating and using lottie animations, while this aims at providing a description of the file format itself.

It would really be helpful if some of these resources were listed as to make this statement you must be aware of what these resources are and people coming to this, like myself, don't 😭 

Thank you <3

**Comment by mbasaglia** [comment]
If you want to create lotties, I suggest my editor: https://glaxnimate.mattbas.org/
You can also check this list with a bunch of tools you can use: https://lottiefiles.com/integrations

To search for existing lotties you can use LottieFiles: https://lottiefiles.com/featured

To play a lottie, you can check the players listed here: https://lottiefiles.com/what-is-lottie.
For the web the you can use lottie-web: https://github.com/airbnb/lottie-web#html-player-installation
