### ISSUE TITLE
wrong ry.a (animated) value in docs/examples/3d_layers.json

### ISSUE THREAD

**Issue by Aidosmf** [LottieFiles/lottie-docs#29]
According to [lottie-docs/schema](https://lottiefiles.github.io/lottie-docs/schema), the `ry.a` has to be "0" when `ry.k` is "static-value", currently the `ry.a` equals "1"

the file reference: [3d_layers.json](https://github.com/LottieFiles/lottie-docs/blob/main/docs/examples/3d_layers.json#L26)

**Comment by mbasaglia** [comment]
fixed
