### ISSUE TITLE
"shapes" prop in a layer?

### ISSUE THREAD

**Issue by Aidosmf** [LottieFiles/lottie-docs#31]
According to lottie-docs/schema, "shapes" prop doesn't exist in "Null Layer", but it exists in https://github.com/LottieFiles/lottie-docs/blob/main/docs/examples/3d_parenting.json#L128, should it be removed?

https://lottiefiles.github.io/lottie-docs/playground/json_editor/ does not recognize it as well.

**Comment by mbasaglia** [comment]
fixed (changed to ty: 4)
