### ISSUE TITLE
mn (match-name) property in an asset-precomposition?

### ISSUE THREAD

**Issue by Aidosmf** [LottieFiles/lottie-docs#32]
according to lottie-docs/schema, "mn" doesn't exist in an asset-precomposition but it exists in https://github.com/LottieFiles/lottie-docs/blob/main/docs/examples/auto_orient.json#L13, should it be removed or the schema missing it?

https://lottiefiles.github.io/lottie-docs/playground/json_editor/ throws an error as well

**Comment by mbasaglia** [comment]
fixed
