### ISSUE TITLE
"np" prop in "effects" examples

### ISSUE THREAD

**Issue by Aidosmf** [LottieFiles/lottie-docs#33]
According to lottie-docs/schema, the `np` (NumberOfProperties) prop doesn't exists in "custom-effects", but there is one in 

- https://github.com/LottieFiles/lottie-docs/blob/main/docs/examples/effects-bulge.json#L76
- https://github.com/LottieFiles/lottie-docs/blob/main/docs/examples/effects-matte3-image.json#L41
- https://github.com/LottieFiles/lottie-docs/blob/main/docs/examples/effects-matte3.json#L65
- https://github.com/LottieFiles/lottie-docs/blob/main/docs/examples/effects-wave.json#L76

JSON_EDITOR throws errors as well

**Comment by mbasaglia** [comment]
added it
