### ISSUE TITLE
Request: json editor with URL parameter that accept json lottie

### ISSUE THREAD

**Issue by AmirulOm** [LottieFiles/lottie-docs#34]
Would be nice to share links on the json editor so that we can share the json view to others. One way is to have the URL to accept query parameter (maybe perhaps in base64 encoded) and in which it would decrypt the json and paste in the viewer.

**Comment by mbasaglia** [comment]
I've added the support to pass a url like this:

    json_editor/?url=https://url/to/lottie.json
