### ISSUE TITLE
Styling issues on large screens

### ISSUE THREAD

**Issue by mbasaglia** [LottieFiles/lottie-docs#39]
* the nav menu at the is very far to the side.
* the JSON editor is not centered, unlike other pages
* in advanced_interactions the examples are way too large

**Comment by mbasaglia** [comment]
This is on a 4k monitor btw

**Comment by mbasaglia** [comment]
Also, there are some visual bugs on the advanced interactions page:

![Screenshot_20221203_164248](https://user-images.githubusercontent.com/2465791/205449345-ae756e03-b8ed-43b2-a0eb-cda8623ff3fa.png)

**Comment by AmirulOm** [comment]
i have fixed the width layout, looking into the advanced interaction bugs

**Comment by AmirulOm** [comment]
This is now fixed.
