### ISSUE TITLE
Metadata "k" invalid type error

### ISSUE THREAD

**Issue by Antonio225t** [LottieFiles/lottie-docs#45]
In the `Advanced Concept` it is defined that `k` is an array of strings but ALSO defined as only string.
```
"anyOf": [
                    {
                        "properties": {
                            "k": {
                                "title": "Keywords",
                                "type": "array",
                                "items": {
                                    "type": "string"
                                }
                            }
                        }
                    },
                    {
                        "properties": {
                            "k": {
                                "title": "Keywords",
                                "type": "string"
                            }
                        }
                    }
                ]
```
Can someone fix this? (Also correct me if I am wrong, this is the cause of the error right? Because when I input `k` in `metadata` and specify that it is a string, it gives me an error saying that it is an array of strings, and if I specify it is an array of strings it says it's a string, I looked up in the schema and find this wich I don't know if it means it could be a string AND an array of strings or it's just an error that someone forgot to delete the second "properties" Object).

**Comment by mbasaglia** [comment]
The schema means either definitions are fine, if you are talking about the json editor, it sometimes gets confused by complex rules

**Comment by Antonio225t** [comment]
I understand now. Thank you and sorry if this issue did stay open for a long time.
Good luck with this big project ❤👍.
